# makefile
# Created on: 28.05.2021
#     Author: folz

#CFLAGS =  -g -std=c++20 -pedantic -Walla -Wextra

all: LinListTst

LinListTst: LinListTst.cpp LinList.o ListElement.o

LinList.o: LinList.cpp LinList.h ListElement.h

ListElement.o: ListElement.cpp ListElement.h

-include ../make-rules
